// constants/workers.ts
import { Worker } from "@/types/worker"

export const WORKERS_DATA: Worker[] = [
  {
    id: 1,
    name: "Somchai Prakobkit",
    role: "Housekeeper",
    rating: 4.9,
    reviews: 127,
    price: 15000,
    image: "/workers/worker-1.jpg",
    verified: true,
    experience: "8 years",
    location: "Bangkok",
    availability: "Full-time",
    languages: ["Thai", "English"],
    skills: ["Deep Cleaning", "Laundry", "Ironing", "Organization"],
  },
  {
    id: 2,
    name: "Nara Suwannarat",
    role: "Cook",
    rating: 4.8,
    reviews: 98,
    price: 18000,
    image: "/workers/worker-2.jpg",
    verified: true,
    experience: "6 years",
    location: "Bangkok",
    availability: "Full-time",
    languages: ["Thai", "English", "Chinese"],
    skills: ["Thai Cuisine", "International Cuisine", "Meal Planning", "Dietary Requirements"],
  },
  {
    id: 3,
    name: "Preecha Mongkol",
    role: "Driver",
    rating: 4.7,
    reviews: 85,
    price: 16000,
    image: "/workers/worker-3.jpg",
    verified: true,
    experience: "10 years",
    location: "Bangkok",
    availability: "Full-time",
    languages: ["Thai", "English"],
    skills: ["Safe Driving", "Vehicle Maintenance", "Route Planning", "Airport Transfers"],
  },
  {
    id: 4,
    name: "Apinya Channarong",
    role: "Nanny",
    rating: 4.95,
    reviews: 142,
    price: 20000,
    image: "/workers/worker-4.jpg",
    verified: true,
    experience: "12 years",
    location: "Bangkok",
    availability: "Live-in",
    languages: ["Thai", "English"],
    skills: ["Childcare", "Educational Activities", "First Aid", "Baby Care"],
  },
  {
    id: 5,
    name: "Manee Rattanaporn",
    role: "Housekeeper",
    rating: 4.6,
    reviews: 73,
    price: 13000,
    image: "/workers/worker-5.jpg",
    verified: false,
    experience: "4 years",
    location: "Chiang Mai",
    availability: "Part-time",
    languages: ["Thai"],
    skills: ["Cleaning", "Laundry", "Basic Cooking"],
  },
  {
    id: 6,
    name: "Wiriya Thepsuwan",
    role: "Gardener",
    rating: 4.75,
    reviews: 56,
    price: 12000,
    image: "/workers/worker-6.jpg",
    verified: true,
    experience: "7 years",
    location: "Bangkok",
    availability: "Part-time",
    languages: ["Thai"],
    skills: ["Lawn Care", "Plant Care", "Landscaping", "Pest Control"],
  },
  {
    id: 7,
    name: "Suda Boontham",
    role: "Cook",
    rating: 4.85,
    reviews: 109,
    price: 17000,
    image: "/workers/worker-7.jpg",
    verified: true,
    experience: "9 years",
    location: "Bangkok",
    availability: "Full-time",
    languages: ["Thai", "English"],
    skills: ["Thai Cuisine", "Western Cuisine", "Baking", "Special Events"],
  },
  {
    id: 8,
    name: "Kanya Wongsuwan",
    role: "Nanny",
    rating: 4.9,
    reviews: 134,
    price: 19000,
    image: "/workers/worker-8.jpg",
    verified: true,
    experience: "11 years",
    location: "Chiang Mai",
    availability: "Live-in",
    languages: ["Thai", "English", "Mandarin"],
    skills: ["Childcare", "Tutoring", "Special Needs", "Newborn Care"],
  },
  {
    id: 9,
    name: "Somsak Petcharat",
    role: "Driver",
    rating: 4.65,
    reviews: 67,
    price: 14000,
    image: "/workers/worker-9.jpg",
    verified: false,
    experience: "5 years",
    location: "Bangkok",
    availability: "Part-time",
    languages: ["Thai"],
    skills: ["City Navigation", "Safe Driving", "Car Maintenance"],
  },
  {
    id: 10,
    name: "Rattana Saengchai",
    role: "Housekeeper",
    rating: 4.8,
    reviews: 91,
    price: 14500,
    image: "/workers/worker-10.jpg",
    verified: true,
    experience: "6 years",
    location: "Bangkok",
    availability: "Live-out",
    languages: ["Thai", "English"],
    skills: ["Deep Cleaning", "Organization", "Laundry", "Pet Care"],
  },
  {
    id: 11,
    name: "Chanida Klahan",
    role: "Cook",
    rating: 4.7,
    reviews: 78,
    price: 16500,
    image: "/workers/worker-11.jpg",
    verified: true,
    experience: "5 years",
    location: "Chiang Mai",
    availability: "Part-time",
    languages: ["Thai"],
    skills: ["Thai Cuisine", "Vegetarian Cooking", "Meal Prep"],
  },
  {
    id: 12,
    name: "Wasan Nopparat",
    role: "Gardener",
    rating: 4.55,
    reviews: 44,
    price: 11000,
    image: "/workers/worker-12.jpg",
    verified: false,
    experience: "3 years",
    location: "Bangkok",
    availability: "Part-time",
    languages: ["Thai"],
    skills: ["Lawn Mowing", "Watering", "Basic Maintenance"],
  },
]

// Filter and Sort options
export const SERVICE_TYPES = [
  "Housekeeper",
  "Cook",
  "Nanny",
  "Gardener",
  "Driver"
] as const

export const EXPERIENCE_RANGES = [
  { label: "0-1 years", min: 0, max: 1 },
  { label: "1-3 years", min: 1, max: 3 },
  { label: "3-5 years", min: 3, max: 5 },
  { label: "5+ years", min: 5, max: 100 },
] as const

export const AVAILABILITY_OPTIONS = [
  "Full-time",
  "Part-time",
  "Live-in",
  "Live-out"
] as const

export const RATING_OPTIONS = [
  { label: "4.5+", value: 4.5 },
  { label: "4.0+", value: 4.0 },
  { label: "3.5+", value: 3.5 },
  { label: "3.0+", value: 3.0 },
] as const

export const SORT_OPTIONS = [
  { value: "recommended", label: "Recommended" },
  { value: "price-low", label: "Price: Low to High" },
  { value: "price-high", label: "Price: High to Low" },
  { value: "rating", label: "Highest Rated" },
  { value: "experience", label: "Most Experienced" },
] as const

export type SortOption = typeof SORT_OPTIONS[number]['value']